# Generated by Django 5.1 on 2024-08-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
